name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Sistem Araçlarını Kur
      run: |
        sudo apt-get update && sudo apt-get install -y cmake
        chmod +x android/gradlew

    - name: Hatalı Dosyaları Temizle ve Bypass Et
      run: |
        rm -f android/gradle.properties
        echo "org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m" > android/gradle.properties
        echo "android.useAndroidX=true" >> android/gradle.properties
        echo "android.enableJetifier=true" >> android/gradle.properties
        echo "kotlin.jvm.target=17" >> android/gradle.properties
        
        find . -type f -exec sed -i 's/"-Xmx64m"//g' {} +
        find . -type f -exec sed -i 's/"-Xms64m"//g' {} +
        find . -type f -exec sed -i 's/-Xmx64m//g' {} +
        find . -type f -exec sed -i 's/-Xms64m//g' {} +

    - name: Build with Gradle
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon -Dorg.gradle.java.home=$JAVA_HOME_17_X64

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Super3-RazerEdge-APK
        path: android/app/build/outputs/apk/debug/app-debug.apk
